# Functions that should be executed before the build script is run
build:
  image: alteved2v/qt6-android-aqt:latest
  script:
    - mkdir build
    - mkdir public
    - qt-cmake ./ -B ./build -G Ninja #-DCMAKE_BUILD_TYPE=MinSizeRel
    - cmake --build ./build

  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      #- public
      - build/android-build/build/outputs/apk/debug/android-build-debug.apk
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


pages:
  image: alteved2v/qt6-wasm-aqt:latest
  before_script:
    - source emsdk_env.sh
  script:
    - mkdir build
    - mkdir public
    - qt-cmake ./ -B ./build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel
    - cmake --build ./build
    # Should exist better way to do this
    - ls build
    - cp build/appstupidNotes.js build/appstupidNotes.wasm build/qtloader.js build/qtlogo.svg public/
    - cp build/appstupidNotes.html public/index.html
    #- cp favicon.ico public/favicon.ico

  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
